# Generated by Django 3.2.3 on 2021-06-03 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='person_media_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='person_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_media', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
                ('type_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person_media_type')),
            ],
        ),
        migrations.CreateModel(
            name='person_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_audit_type', models.IntegerField()),
                ('cpf_new', models.CharField(max_length=14, unique=True)),
                ('cpf_old', models.CharField(max_length=14, null=True)),
                ('last_update', models.DateTimeField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person_type'),
        ),
    ]
