# Generated by Django 3.2.3 on 2021-06-03 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 22, 22, 14, 853423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person_audit',
            name='cpf_new',
            field=models.CharField(max_length=14),
        ),
    ]
