# Generated by Django 3.2.3 on 2021-06-03 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210603_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 22, 44, 10, 633099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person_audit',
            name='cpf_old',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
