# Generated by Django 3.2.3 on 2021-06-03 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210603_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 23, 40, 39, 180127, tzinfo=utc)),
        ),
    ]
